#!/usr/bin/env python3
"""Landing page + WebMCP manifest generator.

Consumes the JSON produced by ``irue_scanner.py`` and writes:

  <output-dir>/index.html                 self-contained interactive landing page
  <output-dir>/.well-known/webmcp.json    WebMCP tool manifest for agent discovery
  <output-dir>/.well-known/mcp.json       alias of the manifest for MCP-style clients
  demo_landing_page.html                  copy of index.html in the CWD (legacy name)
  .well-known/webmcp.json                 copy of the manifest in the CWD (legacy path)

Standard library only. No network access.

Usage:
    landing_page_generator.py repo_profile.json [--output-dir DIST] [--title T] [--base-url URL]
"""
from __future__ import annotations

import argparse
import html
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

WEBMCP_SCHEMA = "https://webmcp.dev/schemas/manifest/v1.json"

LANG_COLORS = {
    "Python": "#3572A5", "JavaScript": "#f1e05a", "TypeScript": "#3178c6", "Go": "#00ADD8",
    "Rust": "#dea584", "Java": "#b07219", "Kotlin": "#A97BFF", "C#": "#178600", "Ruby": "#701516",
    "PHP": "#4F5D95", "Swift": "#F05138", "C": "#555555", "C++": "#f34b7d", "Shell": "#89e051",
    "PowerShell": "#012456", "HTML": "#e34c26", "CSS": "#563d7c", "SCSS": "#c6538c", "SQL": "#e38c00",
    "YAML": "#cb171e", "JSON": "#292929", "TOML": "#9c4221", "Markdown": "#083fa1",
    "Dockerfile": "#384d54", "Terraform": "#7B42BC", "Protobuf": "#4a6fa5", "Dart": "#00B4AB", "Lua": "#000080",
}


def esc(value) -> str:
    return html.escape("" if value is None else str(value), quote=True)


# --------------------------------------------------------------------------- manifest
def build_manifest(profile: dict, base_url: str) -> dict:
    ident = profile["identity"]
    tools = []
    for t in profile.get("webmcp_tools", []):
        tools.append({
            "name": t["name"],
            "description": t["description"],
            "inputSchema": t["inputSchema"],
            "annotations": {"readOnlyHint": t["kind"] in ("python_function",), "source": t["source"], "kind": t["kind"]},
        })
    page_url = f"{base_url.rstrip('/')}/" if base_url else "/"
    return {
        "$schema": WEBMCP_SCHEMA,
        "schemaVersion": "1.0",
        "name": ident["name"],
        "description": ident.get("description") or f"Interactive profile of {ident['name']} generated by IRUE.",
        "version": (ident.get("commit") or "")[:12] or "0.0.0",
        "homepage": page_url,
        "repository": ident.get("repository"),
        "license": ident.get("license"),
        "generatedAt": profile["generated_at"],
        "generator": {"name": "Autonomous-Agentic-Workflows/central-actions irue-scan", "profileSchema": profile["schema_version"]},
        "capabilities": {"tools": {"listChanged": False}, "resources": {"subscribe": False}},
        "tools": tools,
        "resources": [
            {"uri": f"{page_url}repo_profile.json", "name": "repo_profile", "mimeType": "application/json",
             "description": "Full IRUE repository profile (languages, manifests, AST, workflows)."},
            {"uri": page_url, "name": "landing_page", "mimeType": "text/html",
             "description": "Human-readable landing page for this repository."},
        ],
        "metadata": {
            "languages": [lang["name"] for lang in profile["languages"]],
            "entryPoints": profile["python_ast"]["entry_points"],
            "workflows": [w["name"] for w in profile["workflows"]],
            "filesScanned": profile["stats"]["files_scanned"],
        },
    }


# --------------------------------------------------------------------------- html
def render_page(profile: dict, manifest: dict, title: str | None) -> str:
    ident = profile["identity"]
    name = title or ident["name"]
    desc = ident.get("description") or manifest["description"]
    langs = profile["languages"][:8]
    ast_totals = profile["python_ast"]["totals"]
    tools = manifest["tools"]
    workflows = profile["workflows"]
    manifests = profile["manifests"][:12]
    modules = [m for m in profile["python_ast"]["modules"] if m.get("classes") or m.get("functions")][:12]
    generated = datetime.fromisoformat(profile["generated_at"]).astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lang_bar = "".join(
        f'<span class="seg" style="width:{max(lang["share"] * 100, 1.5):.2f}%;background:{LANG_COLORS.get(lang["name"], "#8b8b8b")}" title="{esc(lang["name"])} {lang["share"] * 100:.1f}%"></span>'
        for lang in langs)
    lang_legend = "".join(
        f'<li><i style="background:{LANG_COLORS.get(lang["name"], "#8b8b8b")}"></i>{esc(lang["name"])} <b>{lang["share"] * 100:.1f}%</b> <small>{lang["files"]} files</small></li>'
        for lang in langs)

    stat_cards = [
        ("Files scanned", profile["stats"]["files_scanned"]),
        ("Languages", len(profile["languages"])),
        ("Python modules", ast_totals["modules"]),
        ("Public functions", ast_totals["functions"]),
        ("Classes", ast_totals["classes"]),
        ("Workflows", len(workflows)),
        ("WebMCP tools", len(tools)),
        ("Manifests", len(profile["manifests"])),
    ]
    stats_html = "".join(f'<div class="stat"><span class="n">{esc(v)}</span><span class="l">{esc(k)}</span></div>' for k, v in stat_cards)

    def manifest_row(m: dict) -> str:
        d = m.get("details") or {}
        bits = []
        for key in ("name", "version", "module", "requires_python", "go"):
            if d.get(key):
                bits.append(f"{key}: {d[key]}")
        for key in ("dependencies", "devDependencies", "count", "requires"):
            if d.get(key):
                bits.append(f"{key}: {d[key]}")
        if d.get("base_images"):
            bits.append("FROM " + ", ".join(d["base_images"][:3]))
        if d.get("expose"):
            bits.append("EXPOSE " + ", ".join(d["expose"]))
        if d.get("scripts"):
            bits.append("scripts: " + ", ".join(list(d["scripts"])[:6]))
        if d.get("console_scripts"):
            bits.append("console_scripts: " + ", ".join(list(d["console_scripts"])[:6]))
        if d.get("targets"):
            bits.append("targets: " + ", ".join(d["targets"][:8]))
        return f'<tr><td><code>{esc(m["path"])}</code></td><td>{esc(m["type"])}</td><td class="muted">{esc(" · ".join(bits)) or "—"}</td></tr>'

    manifests_html = "".join(manifest_row(m) for m in manifests) or '<tr><td colspan="3" class="muted">No manifests detected</td></tr>'

    def tool_card(t: dict) -> str:
        props = t["inputSchema"].get("properties", {})
        req = set(t["inputSchema"].get("required", []))
        params = "".join(
            f'<li><code>{esc(p)}</code> <em>{esc(s.get("type", "string"))}</em>{" <b>required</b>" if p in req else ""}</li>'
            for p, s in props.items())
        return (f'<article class="tool" data-tool="{esc(t["name"])}"><header><code>{esc(t["name"])}</code>'
                f'<span class="pill">{esc(t["annotations"]["kind"].replace("_", " "))}</span></header>'
                f'<p>{esc(t["description"])}</p>'
                f'{"<ul class=params>" + params + "</ul>" if params else ""}'
                f'<footer class="muted">{esc(t["annotations"]["source"])}</footer></article>')

    tools_html = "".join(tool_card(t) for t in tools) or '<p class="muted">No tool candidates discovered. Add docstrings to public functions or scripts to expose them.</p>'

    wf_html = "".join(
        f'<li><b>{esc(w["name"])}</b> <code>{esc(w["path"])}</code><br><small class="muted">on: {esc(", ".join(w["triggers"]) or "—")}'
        f'{" · reusable" if w["reusable"] else ""}</small></li>' for w in workflows) or '<li class="muted">No GitHub Actions workflows</li>'

    def module_block(m: dict) -> str:
        items = [f'<li class="cls">class <b>{esc(c["name"])}</b>{" — " + esc(c["doc"].splitlines()[0]) if c.get("doc") else ""}</li>' for c in m["classes"][:6]]
        items += [f'<li>def <b>{esc(f["name"])}</b>({esc(", ".join(p["name"] for p in f["params"]))}){" — " + esc(f["doc"].splitlines()[0]) if f.get("doc") else ""}</li>' for f in m["functions"][:8]]
        return f'<details><summary><code>{esc(m["path"])}</code>{" <span class=pill>entry point</span>" if m.get("has_main_guard") else ""}</summary><ul>{"".join(items)}</ul></details>'

    modules_html = "".join(module_block(m) for m in modules) or '<p class="muted">No Python modules with public API surface.</p>'

    repo_link = f'<a class="btn ghost" href="{esc(ident["repository"])}" rel="noopener">Repository</a>' if ident.get("repository") else ""
    manifest_json = json.dumps(manifest).replace("</", "<\\/")

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(name)} — IRUE profile</title>
<meta name="description" content="{esc(desc[:160])}">
<link rel="webmcp-manifest" href=".well-known/webmcp.json">
<link rel="alternate" type="application/json" href="repo_profile.json" title="IRUE repository profile">
<style>
:root{{--bg:#0b0d12;--panel:#12161f;--line:#232a38;--fg:#e7ebf3;--muted:#8b95a9;--accent:#7c9cff;--accent2:#5ee6b7;--radius:14px}}
@media (prefers-color-scheme:light){{:root{{--bg:#f6f7fb;--panel:#fff;--line:#e3e7ef;--fg:#111827;--muted:#5b6474;--accent:#3b5bdb;--accent2:#0f9d75}}}}
*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}
body{{margin:0;font:16px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Inter,sans-serif;background:var(--bg);color:var(--fg)}}
a{{color:var(--accent);text-decoration:none}}a:hover{{text-decoration:underline}}
code{{font:.9em ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:rgba(124,156,255,.12);padding:.1em .4em;border-radius:6px}}
.wrap{{max-width:1080px;margin:0 auto;padding:0 20px}}
header.hero{{padding:64px 0 40px;border-bottom:1px solid var(--line);background:radial-gradient(900px 300px at 20% -10%,rgba(124,156,255,.18),transparent),radial-gradient(700px 300px at 90% 0,rgba(94,230,183,.14),transparent)}}
.eyebrow{{text-transform:uppercase;letter-spacing:.14em;font-size:.72rem;color:var(--muted);margin-bottom:12px}}
h1{{font-size:clamp(2rem,4.5vw,3.2rem);line-height:1.1;margin:0 0 14px;letter-spacing:-.02em}}
.lede{{font-size:1.15rem;color:var(--muted);max-width:720px;margin:0 0 26px}}
.actions{{display:flex;gap:10px;flex-wrap:wrap}}
.btn{{display:inline-block;padding:10px 16px;border-radius:10px;background:var(--accent);color:#fff;font-weight:600;border:1px solid transparent}}
.btn.ghost{{background:transparent;color:var(--fg);border-color:var(--line)}}.btn:hover{{text-decoration:none;filter:brightness(1.08)}}
nav.toc{{position:sticky;top:0;z-index:5;background:color-mix(in srgb,var(--bg) 88%,transparent);backdrop-filter:blur(8px);border-bottom:1px solid var(--line)}}
nav.toc ul{{list-style:none;display:flex;gap:4px;margin:0;padding:8px 0;overflow-x:auto}}nav.toc a{{display:block;padding:6px 12px;border-radius:8px;color:var(--muted);font-size:.9rem;white-space:nowrap}}nav.toc a:hover{{background:var(--panel);color:var(--fg);text-decoration:none}}
section{{padding:44px 0;border-bottom:1px solid var(--line)}}h2{{font-size:1.5rem;margin:0 0 6px;letter-spacing:-.01em}}.sub{{color:var(--muted);margin:0 0 22px}}
.stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px}}
.stat{{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);padding:16px}}.stat .n{{display:block;font-size:1.8rem;font-weight:700;letter-spacing:-.02em}}.stat .l{{color:var(--muted);font-size:.85rem}}
.bar{{display:flex;height:12px;border-radius:999px;overflow:hidden;border:1px solid var(--line);background:var(--panel)}}.bar .seg{{display:block;height:100%}}
.legend{{list-style:none;display:flex;flex-wrap:wrap;gap:10px 22px;padding:0;margin:14px 0 0}}.legend i{{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px;vertical-align:middle}}.legend small{{color:var(--muted)}}
table{{width:100%;border-collapse:collapse;background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);overflow:hidden}}th,td{{text-align:left;padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top;font-size:.93rem}}th{{color:var(--muted);font-weight:600;font-size:.8rem;text-transform:uppercase;letter-spacing:.06em}}tr:last-child td{{border-bottom:0}}
.muted{{color:var(--muted)}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}}
.tool{{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius);padding:16px;display:flex;flex-direction:column;gap:8px}}.tool header{{display:flex;justify-content:space-between;align-items:center;gap:8px;flex-wrap:wrap}}.tool header code{{overflow-wrap:anywhere;min-width:0}}.tool p{{margin:0;font-size:.95rem}}.tool footer{{font-size:.78rem;margin-top:auto}}
.params{{list-style:none;padding:0;margin:0;font-size:.85rem;display:flex;flex-wrap:wrap;gap:6px}}.params li{{background:rgba(94,230,183,.1);border:1px solid var(--line);border-radius:8px;padding:2px 8px}}.params em{{color:var(--muted);font-style:normal}}
.pill{{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;background:rgba(94,230,183,.14);color:var(--accent2);border-radius:999px;padding:3px 9px;white-space:nowrap}}
details{{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:10px 14px;margin-bottom:8px}}summary{{cursor:pointer;font-weight:600}}details ul{{margin:8px 0 4px;padding-left:18px;font-size:.92rem}}details li{{margin:2px 0}}
ul.wf{{list-style:none;padding:0;margin:0;display:grid;gap:10px;grid-template-columns:repeat(auto-fill,minmax(300px,1fr))}}ul.wf li{{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:12px 14px}}
.search{{width:100%;max-width:420px;padding:10px 14px;border-radius:10px;border:1px solid var(--line);background:var(--panel);color:var(--fg);font-size:.95rem;margin-bottom:16px}}
footer.site{{padding:28px 0 48px;color:var(--muted);font-size:.85rem}}
#webmcp-status{{font-size:.8rem;color:var(--muted)}}#webmcp-status.ok{{color:var(--accent2)}}
</style>
</head>
<body>
<header class="hero"><div class="wrap">
  <div class="eyebrow">IRUE repository profile · generated {esc(generated)}</div>
  <h1>{esc(name)}</h1>
  <p class="lede">{esc(desc) or "Interactive, agent-readable overview of this repository."}</p>
  <div class="actions">
    {repo_link}
    <a class="btn" href=".well-known/webmcp.json">WebMCP manifest</a>
    <a class="btn ghost" href="repo_profile.json">repo_profile.json</a>
  </div>
  <p id="webmcp-status">WebMCP: checking browser support…</p>
</div></header>

<nav class="toc"><div class="wrap"><ul>
  <li><a href="#overview">Overview</a></li><li><a href="#stack">Stack</a></li><li><a href="#tools">Agent tools</a></li>
  <li><a href="#api">API surface</a></li><li><a href="#manifests">Manifests</a></li><li><a href="#workflows">Workflows</a></li>
</ul></div></nav>

<main class="wrap">
<section id="overview"><h2>Overview</h2><p class="sub">What the IRUE scanner found at a glance.</p><div class="stats">{stats_html}</div></section>

<section id="stack"><h2>Language stack</h2><p class="sub">Share of source bytes by language.</p>
  <div class="bar">{lang_bar}</div><ul class="legend">{lang_legend}</ul></section>

<section id="tools"><h2>Agent tools <span class="pill">WebMCP</span></h2>
  <p class="sub">{len(tools)} callable capabilities discovered and published in <code>.well-known/webmcp.json</code>. Browsers with WebMCP register them automatically.</p>
  <input class="search" type="search" id="tool-filter" placeholder="Filter tools…" aria-label="Filter tools">
  <div class="grid" id="tool-grid">{tools_html}</div></section>

<section id="api"><h2>Python API surface</h2><p class="sub">Public classes and functions extracted from the AST.</p>{modules_html}</section>

<section id="manifests"><h2>Manifests</h2><p class="sub">Build, dependency and deployment descriptors.</p>
  <table><thead><tr><th>Path</th><th>Type</th><th>Details</th></tr></thead><tbody>{manifests_html}</tbody></table></section>

<section id="workflows"><h2>CI/CD workflows</h2><p class="sub">GitHub Actions detected in <code>.github/workflows</code>.</p><ul class="wf">{wf_html}</ul></section>
</main>

<footer class="site"><div class="wrap">Generated by <b>Autonomous-Agentic-Workflows/central-actions</b> · irue-scan · profile schema {esc(profile["schema_version"])}
{" · commit <code>" + esc(ident["commit"][:12]) + "</code>" if ident.get("commit") else ""} · license {esc(ident.get("license") or "unspecified")}</div></footer>

<script id="webmcp-manifest" type="application/json">{manifest_json}</script>
<script>
(function(){{
  var manifest = JSON.parse(document.getElementById('webmcp-manifest').textContent);
  var status = document.getElementById('webmcp-status');
  // Tool filter
  var input = document.getElementById('tool-filter');
  if (input) input.addEventListener('input', function(){{
    var q = input.value.toLowerCase();
    document.querySelectorAll('#tool-grid .tool').forEach(function(el){{
      el.style.display = el.textContent.toLowerCase().indexOf(q) > -1 ? '' : 'none';
    }});
  }});
  // WebMCP: register declared tools with the browser agent context when supported.
  var ctx = navigator.modelContext;
  if (ctx && typeof ctx.registerTool === 'function') {{
    manifest.tools.forEach(function(t){{
      try {{
        ctx.registerTool({{
          name: t.name, description: t.description, inputSchema: t.inputSchema,
          execute: function(args){{
            return Promise.resolve({{ content: [{{ type: 'text', text: 'Tool "' + t.name + '" is descriptive only on this landing page. Source: ' + t.annotations.source + '. Args: ' + JSON.stringify(args || {{}}) }}] }});
          }}
        }});
      }} catch (e) {{ console.warn('WebMCP registerTool failed', t.name, e); }}
    }});
    status.textContent = 'WebMCP: ' + manifest.tools.length + ' tools registered with navigator.modelContext';
    status.className = 'ok';
  }} else {{
    status.textContent = 'WebMCP: manifest published at .well-known/webmcp.json (browser API not detected)';
  }}
}})();
</script>
</body>
</html>
"""


# --------------------------------------------------------------------------- main
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("profile", help="repo_profile.json from irue_scanner.py")
    ap.add_argument("--output-dir", default="dist")
    ap.add_argument("--title", default=None)
    ap.add_argument("--base-url", default="")
    ap.add_argument("--no-legacy-copies", action="store_true", help="skip demo_landing_page.html and ./.well-known copies")
    args = ap.parse_args(argv)

    profile = json.loads(Path(args.profile).read_text(encoding="utf-8"))
    out = Path(args.output_dir)
    (out / ".well-known").mkdir(parents=True, exist_ok=True)

    manifest = build_manifest(profile, args.base_url)
    page = render_page(profile, manifest, args.title)

    (out / "index.html").write_text(page, encoding="utf-8")
    manifest_text = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    (out / ".well-known" / "webmcp.json").write_text(manifest_text, encoding="utf-8")
    (out / ".well-known" / "mcp.json").write_text(manifest_text, encoding="utf-8")

    if not args.no_legacy_copies:
        Path("demo_landing_page.html").write_text(page, encoding="utf-8")
        Path(".well-known").mkdir(exist_ok=True)
        shutil.copyfile(out / ".well-known" / "webmcp.json", Path(".well-known") / "webmcp.json")

    print(f"wrote {out / 'index.html'} ({len(page):,} bytes) and {out / '.well-known' / 'webmcp.json'} "
          f"({len(manifest['tools'])} tools)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
